### ISSUE TITLE
Research centralized data storage solution (database)

### ISSUE THREAD

**Issue by tommyxchow** [Prakshal-Jain/Zeal#12]

**Comment by tommyxchow** [comment]
Possible Database Candidates
- SQLite (current)
- Amazon S3/DynamoDB
- MongoDB
- Firebase/Supabase
- PostgreSQL (Relational)
- Redis (in-memory)

**Comment by tommyxchow** [comment]
Data that will be stored:

User/organizer
- Auth (email, username, and password)
- Profile information
- Chat messages
- Team members
- Recommendations in gotcha center
- Saved events and recommendations

Events:
- Details and information
- Participants

**Comment by tommyxchow** [comment]
Things to consider

- Pricing & free tiers
- Ease of use & setup
- Developer experience (DX)
- Syntax (SQL vs noSQL)
- Storage types
- Relational or not

**Comment by tommyxchow** [comment]
@aleena-sheikh and I discussed and believe PostgreSQL will be the best solution.

## Relevant links and resources

### PostgreSQL
- [Main site](https://www.postgresql.org/)
- [Documentation](https://www.postgresql.org/docs/current/)
- [Tutorials](https://www.postgresql.org/docs/online-resources/)
- [Python driver & lib](https://www.psycopg.org/)

### Django
- [PostgreSQL on Django website](https://docs.djangoproject.com/en/3.2/ref/databases/#postgresql-notes)

### Docker

- [Official Docker sample app](https://docs.docker.com/samples/postgresql_service/)
- [Official Docker container](https://hub.docker.com/_/postgres)

**Comment by aleena-sheikh** [comment]
[Dockerize PostgreSQL](https://docs.docker.com/samples/postgresql_service/)
[Quickstart: Django + Postgres on Docker](https://docs.docker.com/samples/django/)
[PostgreSQL as your database in Python applications - heroku](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-python)
[create a postgres database in docker](https://dev.to/andre347/how-to-easily-create-a-postgres-database-in-docker-4moj)
[using python to write to postgres using psycopg](https://www.psycopg.org/docs/install.html)
[Python Postrges Docker template](https://github.com/carlosdg/PythonPostgresDockerTemplate)
