### ISSUE TITLE
As a hackathon event organizer, I want to host events so that participants can find teammates

### ISSUE THREAD

**Issue by Prakshal-Jain** [Prakshal-Jain/Zeal#5]
**Acceptance Tests**

 *Test 1*
1) Sign in successfully 
2) Go to the Menu.
3) Click Host an Event
4) Fill out the event details
5) Send a personalized URL to participants

**Comment by aleena-sheikh** [comment]
**Acceptance Tests**

Sign in successfully 
Go to the Menu.
Click Host an Event
Fill out the event details
Send a personalized URL to participants
