### ISSUE TITLE
As a student, I want to be able to see other ideas in the Gotcha Center so that I can brainstorm new ideas

### ISSUE THREAD

**Issue by Prakshal-Jain** [Prakshal-Jain/Zeal#6]
**Acceptance Tests**

*Test 1*
1) Add topics to search content like latest or popular projects and news.
2) Delete topics
3) Click Gotcha Center from the sidebar
4) Should get relevant results based on the topics.

*Test 2*
1) Sign in successfully
2) Go to the Menu.
3) Click Gotcha Center
4) View the idea list based on a topic

**Comment by aleena-sheikh** [comment]
Acceptance Tests

Test 1
Sign in successfully
Go to the Menu.
Click Gotcha Center
View the idea list based on a topic
